(defpackage user
  (:use :cl))
(in-package :rest-api)

(mito:deftable user ()
  ((id :col-type (or (:integer) :null) 
       :auto-increment t
       :acessor user-id)
   (name :col-type (:varchar 64)
         :accessor user-name)
   (email :col-type (:varchar 64)
         :acessor user-email)
   (password :col-type (:varchar 1000)
             :acessor user-password)
   (status :col-type (:bool)
           :acessor user-status)
   (kind :col-type (:varchar 64)
         :acessor user-kind))
  (:primary-key id)
  (:auto-pk nil)
  (:unique-keys email))

(defmethod yason:encode-slots progn ((user user))
  (yason:encode-object-element "id" (user-id user))
  (yason:encode-object-element "name" (user-name user))
  (yason:encode-object-element "email" (user-email user))
  (yason:encode-object-element "status" (user-status user))
  (yason:encode-object-element "kind" (user-kind user)))

(defmethod yason:encode ((user user) &optional (stream *standard-output*))
  (yason:with-output (stream)
    (yason:with-object ()
      (yason:encode-slots user))))